### ISSUE TITLE
ValueError: 'Last Update' is not in list

### ISSUE THREAD

**Issue by rdorsch** [AaronWard/covid-19-analysis#27]
I get since today (w/o updating covid-19-analysis)

... importing data:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 59/62 [00:01<00:00, 25.02it/s]
Traceback (most recent call last):
  File "./build/lib/covidify/data_prep.py", line 42, in <module>
    df = github.get()
  File "/home/rd/tmp.nobackup/git/covid-19-analysis/build/lib/covidify/sources/github.py", line 140, in get
    df = get_data(cleaned_sheets)
  File "/home/rd/tmp.nobackup/git/covid-19-analysis/build/lib/covidify/sources/github.py", line 62, in get_data
    header=0, parse_dates=['Last Update'])
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1758, in __init__
    self._set_noconvert_columns()
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1826, in _set_noconvert_columns
    _set(val)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1816, in _set
    x = names.index(x)
ValueError: 'Last Update' is not in list
###

**Comment by AaronWard** [comment]
@rdorsch Hey, i just seen this too. 

This is because JHU unexpectedly just changed there column names for now reason. 

- https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-22-2020.csv

- https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_daily_reports/03-23-2020.csv


I will work on a fix today

**Comment by AaronWard** [comment]
Fixed
